name: CI Build

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches: [ master ]
  workflow_dispatch:
permissions:
  contents: read

env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry
  VERSION: 1.0.0

jobs:
# MAUI Android Build
  build-android:
    runs-on: windows-2022
    name: Android Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
          
      - name: Install MAUI Workloads
        run: |
          dotnet workload install android --ignore-failed-sources
          dotnet workload install maui --ignore-failed-sources
      - name: Restore Dependencies
        run: dotnet restore PursuitTimer

      - name: Build MAUI Android
        run: dotnet build PursuitTimer -c Release -f net6.0-android --no-restore

      - name: Publish MAUI Android
        run: dotnet publish PursuitTimer -c Release -f net6.0-android

      - name: Upload Android Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: android-ci-build
          path: PursuitTimer/bin/Release/net6.0-android/*Signed.a*

# MAUI iOS Build
  build-ios:
    runs-on: macos-12
    name: iOS Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Install MAUI Workloads
        run: |
          dotnet workload install ios --ignore-failed-sources
          dotnet workload install maui --ignore-failed-sources
      - name: Restore Dependencies
        run: dotnet restore PursuitTimer -r ios-arm64

      - name: Import Code-Signing Certificates
        uses: Apple-Actions/import-codesign-certs@v1
        with:
          #p12-file-base64: ${{ secrets.CERTIFICATES_P12_BASE64 }}
          p12-filepath: 'DistributionCertVeloTimePursuitTimer.p12'
          p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
      - name: Download Apple Provisioning Profiles
        uses: Apple-Actions/download-provisioning-profiles@v1
        with:
          bundle-id: 'me.veloti.pursuittimer'
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}

      - name: Build MAUI iOS
        run: dotnet build PursuitTimer -c Release -f net6.0-ios --no-restore

      - name: Publish MAUI iOS
        run: dotnet publish PursuitTimer -c Release -f:net6.0-ios -r ios-arm64

      - name: Upload iOS Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: ios-ci-build
          path: PursuitTimer/bin/Release/net6.0-ios/**/*.app/
      - name: Upload iOS Package
        uses: actions/upload-artifact@v3.0.0
        with:
          name: ios-ci-package
          path: PursuitTimer/bin/Release/net6.0-ios/**/*.ipa

      - name: Make appstore key ready
        run: echo "${{ secrets.APPSTORE_PRIVATE_KEY }}" > Authkey_${{ secrets.APPSTORE_KEY_ID }}.p8
      - name: Publish to App Store
        env:
          API_PRIVATE_KEYS_DIR: .
        run: xcrun altool --upload-package PursuitTimer/bin/Release/net6.0-ios/ios-arm64/publish/PursuitTimer.ipa --type ios --apple-id 1630437751 --bundle-id me.velotimer.pursuittimer --bundle-short-version-string $VERSION --bundle-version ${{ github.run_number}}.${{ github.run_attempt }} --apiKey ${{ secrets.APPSTORE_KEY_ID }} --apiIssuer ${{ secrets.APPSTORE_ISSUER_ID }}
        #run: xcrun altool --upload-app -f PursuitTimer/bin/Release/net6.0-ios/ios-arm64/publish/PursuitTimer.ipa --type ios --apiKey ${{ secrets.APPSTORE_KEY_ID }} --apiIssuer ${{ secrets.APPSTORE_ISSUER_ID }}