
name: Dependency Submission

on:
  workflow_dispatch:
  push:

permissions:
  id-token: write
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
          cache: false
      - name: Install MAUI Workloads
        run: |
          dotnet workload restore
      - name: configure-cache
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306
        with:
          path: ~/.nuget/packages
          key: Linux-nuget-2349583459sdfjhgslkjdhg
          restore-keys: Linux-nuget-
          enableCrossOsArchive: false
          fail-on-cache-miss: false
          lookup-only: false
          save-always: false
        env:
          SKIP_CACHE: 
          DOTNET_ROOT: /usr/share/dotnet
      - name: validate-project
        run: |
          dotnet restore --force PursuitTimer
        env:
          SKIP_CACHE: 
          DOTNET_ROOT: /usr/share/dotnet
      - name: submit-dependency-snapshot
        uses: actions/component-detection-dependency-submission-action@374343effede691df3a5ffaf36b4e7acab919590
        with:
          detectorsCategories: NuGet
          snapshot-sha: ${{ github.sha }}
          snapshot-ref: ${{ github.ref }}
          detector-name: Automatic Dependency Submission
          detector-version: 244344d64fb0
          detector-url: https://github.com/actions/component-detection-dependency-submission-action
          filePath: .
        env:
          SKIP_CACHE: 
          DOTNET_ROOT: /usr/share/dotnet