name: iOS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Install iOS workload
      run: dotnet workload install ios
    - name: Install MAUI workload
      run: dotnet workload install maui
    - name: Restore dependencies
      run: dotnet restore PursuitTimer
    - name: Build
      run: dotnet build PursuitTimer -c Release -f:net6.0-ios --no-restore
    - name: Import Code-Signing Certificates
      uses: Apple-Actions/import-codesign-certs@v1
      with:
        #p12-file-base64: ${{ secrets.CERTIFICATES_P12_BASE64 }}
        p12-filepath: 'DistributionCertVeloTimePursuitTimer.p12'
        p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
    - name: Download Apple Provisioning Profiles
      uses: Apple-Actions/download-provisioning-profiles@v1
      with:
        bundle-id: 'me.veloti.pursuittimer'
        issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
        api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
        api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
    - name: dotnet publish
      run: dotnet publish PursuitTimer -c Release -f:net6.0-ios -r ios-arm64 --no-build
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        path: '**/*.ipa'
